export const COUNTRIES = [
  'Australia',
  'United States',
  'United Kingdom',
  'Canada',
  'Germany',
  'Ireland',
  'Singapore',
  'New Zealand',
  'Netherlands',
  'Spain',
  'France',
  'India',
  'Japan',
  'Brazil',
  'Mexico',
  'Sweden',
  'Switzerland',
  'Poland',
  'South Africa',
  'United Arab Emirates',
] as const
